# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(697, 561)
        font = QFont()
        font.setFamily(u"MS Sans Serif")
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_2 = QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.ID = QSpinBox(self.groupBox)
        self.ID.setObjectName(u"ID")
        self.ID.setGeometry(QRect(40, 30, 141, 22))
        self.ID.setAccelerated(False)
        self.ID.setMaximum(10000000)
        self.Velocidad = QSpinBox(self.groupBox)
        self.Velocidad.setObjectName(u"Velocidad")
        self.Velocidad.setGeometry(QRect(240, 230, 111, 31))
        self.Velocidad.setMaximum(1000000)
        self.groupBox_2 = QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(20, 230, 151, 258))
        self.Verde = QScrollBar(self.groupBox_2)
        self.Verde.setObjectName(u"Verde")
        self.Verde.setGeometry(QRect(90, 20, 17, 191))
        self.Verde.setMaximum(255)
        self.Verde.setOrientation(Qt.Vertical)
        self.Azul = QScrollBar(self.groupBox_2)
        self.Azul.setObjectName(u"Azul")
        self.Azul.setGeometry(QRect(50, 20, 17, 191))
        self.Azul.setMaximum(255)
        self.Azul.setOrientation(Qt.Vertical)
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 220, 31, 16))
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(90, 220, 41, 16))
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 220, 31, 16))
        self.Rojo = QScrollBar(self.groupBox_2)
        self.Rojo.setObjectName(u"Rojo")
        self.Rojo.setGeometry(QRect(10, 23, 17, 191))
        self.Rojo.setMaximum(255)
        self.Rojo.setOrientation(Qt.Vertical)
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 30, 47, 20))
        self.groupBox_3 = QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 60, 361, 71))
        self.label_5 = QLabel(self.groupBox_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 20, 20, 20))
        self.OrigenX = QScrollBar(self.groupBox_3)
        self.OrigenX.setObjectName(u"OrigenX")
        self.OrigenX.setGeometry(QRect(30, 20, 321, 16))
        self.OrigenX.setMaximum(500)
        self.OrigenX.setOrientation(Qt.Horizontal)
        self.label_6 = QLabel(self.groupBox_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 50, 16, 16))
        self.OrigenY = QScrollBar(self.groupBox_3)
        self.OrigenY.setObjectName(u"OrigenY")
        self.OrigenY.setGeometry(QRect(30, 50, 321, 16))
        self.OrigenY.setMaximum(500)
        self.OrigenY.setOrientation(Qt.Horizontal)
        self.groupBox_4 = QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 140, 361, 80))
        self.DestinoX = QScrollBar(self.groupBox_4)
        self.DestinoX.setObjectName(u"DestinoX")
        self.DestinoX.setGeometry(QRect(30, 30, 321, 16))
        self.DestinoX.setMaximum(500)
        self.DestinoX.setOrientation(Qt.Horizontal)
        self.label_7 = QLabel(self.groupBox_4)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 30, 20, 20))
        self.label_8 = QLabel(self.groupBox_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 50, 20, 20))
        self.DestinoY = QScrollBar(self.groupBox_4)
        self.DestinoY.setObjectName(u"DestinoY")
        self.DestinoY.setGeometry(QRect(30, 60, 321, 16))
        self.DestinoY.setMaximum(500)
        self.DestinoY.setOrientation(Qt.Horizontal)
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(170, 230, 71, 31))
        self.Mostrar = QPushButton(self.groupBox)
        self.Mostrar.setObjectName(u"Mostrar")
        self.Mostrar.setGeometry(QRect(200, 410, 151, 71))
        self.salida = QPlainTextEdit(self.groupBox)
        self.salida.setObjectName(u"salida")
        self.salida.setGeometry(QRect(383, 20, 281, 471))
        self.Iniciocap = QPushButton(self.groupBox)
        self.Iniciocap.setObjectName(u"Iniciocap")
        self.Iniciocap.setGeometry(QRect(200, 300, 151, 41))
        self.finalcap = QPushButton(self.groupBox)
        self.finalcap.setObjectName(u"finalcap")
        self.finalcap.setGeometry(QRect(200, 350, 151, 41))

        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 697, 22))
        self.menuCaptura_de_Particulas = QMenu(self.menubar)
        self.menuCaptura_de_Particulas.setObjectName(u"menuCaptura_de_Particulas")
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(6, 14, 7, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(9, 21, 10, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(7, 17, 8, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(3, 7, 3, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(4, 9, 5, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        brush7 = QBrush(QColor(255, 255, 220, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        brush8 = QBrush(QColor(255, 255, 255, 128))
        brush8.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush8)
#endif
        self.menuCaptura_de_Particulas.setPalette(palette)
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuCaptura_de_Particulas.menuAction())

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Particula", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Color(RVA)", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Rojo", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Verde", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Azul", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Origen", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Destino", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Velocidad", None))
        self.Mostrar.setText(QCoreApplication.translate("MainWindow", u"Mostrar", None))
        self.Iniciocap.setText(QCoreApplication.translate("MainWindow", u"Capturar Inicio", None))
        self.finalcap.setText(QCoreApplication.translate("MainWindow", u"Capturar Final", None))
        self.menuCaptura_de_Particulas.setTitle(QCoreApplication.translate("MainWindow", u"Captura de Particulas", None))
    # retranslateUi

